@{
    "The default answer is yes." = "Die Standard-Antwort ist Ja."
    "Remove Application: {0}? [Y/n]" = "Entfernen der Anwendung: {0}? [J/n]"
    "You already removed the following Application: {0}" = "Sie haben die folgende Anwendung bereits entfernt: {0}"
    "Disable Windows Optional Feature: {0}? [Y/n]" = "Deaktivieren des optionalen Windows-Feature: {0}? [J/n]"
    "You already disabled the following Windows Optional Feature: {0}" = "Sie haben das folgende optionale Windows-Feature bereits abgeschaltet: {0}"
    "Disable Firewall Rule: {0}? [Y/n]" = "Deaktivieren der Firewall Regel: {0}? [J/n]"
    "You already disabled the following Firewall Rule: {0}" = "Sie haben die folgende Firewall Regel bereits abgeschaltet: {0}"
    "Disable Service: {0}? [Y/n]" = "Deaktivieren des Dienstes: {0}? [J/n]"
    "You already disabled the following Service: {0}" = "Sie haben den folgenden Dienst bereits abgeschaltet: {0}"
    "Disable Windows Home Groups? [Y/n]" = "Deaktivieren der Windows Heimnetzgruppen Funktion? [J/n]"
    "You already disabled Windows Home Groups." = "Sie haben die Windows Heimnetzgruppen Funktion bereits abgeschaltet."
    "Remove Microsoft OneDrive? [Y/n]" = "Microsoft OneDrive entfernen? [J/n]"
    "You already removed Microsoft OneDrive." = "Sie haben Microsoft OneDrive bereits entfernt."
    "Disable Windows Telemetry? [Y/n]" = "Windows Telemetry abschalten? [J/n]"
    "You already disabled Windows Telemetry." = "Sie haben Windows Telemetry bereits abgeschaltet."
    "Set alternative Network Time Servers? [Y/n]" = "Alternative Netzwerk-Zeitserver setzen? [J/n]"
    "You already set alternative Network Time Servers." = "Sie haben bereits alternative Netzwerk-Zeitserver gesetzt."
    "You may need to restart your computer and run the script again." = "M$([char]0x00F6)glicherweise m$([char]0x00FC)ssen Sie Ihren Computer neu starten und das Skript erneut laufen lassen."
    "You are done, press enter to exit" = "Sie sind fertig dr$([char]0x00FC)cken Sie die Eingabetaste, um zu beenden"
}